# 后端配置
backend:
  name: git-gateway
  repo: I8Zoro8I/zoro_blog  # 你的 用户名/仓库名
  branch: main             # 确认你的分支是 main


# 只有在本地电脑运行时才开启此项，部署前建议注释掉
#local_backend: true

# 媒体文件：图片存放在 docs/public/images
media_folder: "docs/public/images"
# 网页访问图片的路径（对应 VitePress 的访问地址）
public_folder: "/images"

# 内容集合
collections:
  - name: "column"
    label: "文章"
    folder: "docs/column"  # 文章在仓库中的实际路径
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "内容", name: "body", widget: "markdown" }